Update NBengineElephant.cfg
zer0Kerbal/ElephantEngine pull request #38
Opened 2022-04-27 16:12 UTC by AtomikkuSan

Did some performance tweaking.

2022-04-27 16:15 UTC, AtomikkuSan commented
@zer0Kerbal, I've done it. This pull request now goes to the 0.2.99.1-prerelease branch instead of the master branch.

2022-04-28 02:01 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/NBengineElephant.cfg
> +	author = NecroBones, zer0Kerbal, Atomikku
kindly put zer0Kerbal last 

1. original authors
2. subsequent authors
3. current authors in alphabetical order

2022-04-28 02:01 UTC, zer0Kerbal requested changes
one change requested.

2022-04-28 02:05 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/NBengineElephant.cfg
> +	author = NecroBones, zer0Kerbal, Atomikku
will approve and merge once updated.

well done.

2022-04-28 13:45 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/NBengineElephant.cfg
> +	author = NecroBones, zer0Kerbal, Atomikku
Hmm, I always put you before me 'cause it's my project, not yours.

2022-04-28 13:52 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/NBengineElephant.cfg
> +	author = NecroBones, zer0Kerbal, Atomikku
Already done!

2022-05-02 16:10 UTC, AtomikkuSan commented
@zer0Kerbal, can you take a look at the latest commit?

2022-05-02 19:43 UTC, zer0Kerbal approved these changes

2022-05-02 19:46 UTC, merged