QuadAtomic.cfg
zer0Kerbal/ElephantEngine pull request #40
Opened 2022-04-27 16:57 UTC by AtomikkuSan

Still need to add a center nozzle.

2022-04-28 02:08 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	TechRequired = veryHeavyRocketry
maybe bump this to another node on same or higher level?

2022-04-28 02:09 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	entryCost = 86250
how does this adjust entryCost?

2022-04-28 02:16 UTC, zer0Kerbal requested changes
also - might not be so easy to just add another - see how the original author adjusted each model to allow for individual animations/emissives?

2022-04-28 02:16 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	cost = 29250
how does this adjust cost?

2022-04-28 02:16 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	mass = 11.625
has this been adjusted? not just 4xvector - but need to include roughly 25% for the hardware combining them

2022-04-28 02:16 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +		maxThrust = 3000
have you adjusted this for 4 instead of 3?

2022-04-28 02:16 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +		maxThrust = 3000
have you adjusted this for 4 instead of 3?

2022-04-28 02:16 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	name = AT_Quardophant
to keep consistency between existing and new:

NBengineElephant-quad

plus underscores '_' in part.names bad. very very bad. 😄  (how does module manager react (and the game) to part names with underscores? PITA to create patches for them FYI)

2022-04-28 02:16 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +			rate = 9.0
should this be adjusted as well?

2022-04-28 13:26 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	name = AT_Quardophant
Okay, just fixed that!

2022-04-28 13:27 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	TechRequired = veryHeavyRocketry
Okay, which one do you think would work best?

2022-04-28 13:27 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	entryCost = 86250
I don't know, unfortunately...

2022-04-28 13:28 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +			rate = 9.0
Honestly, I don't really care for alternators within engines.

2022-04-29 20:05 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	entryCost = 86250
entryCost is usually something like x8-10 times the cost.

2022-04-29 20:08 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	TechRequired = veryHeavyRocketry
? Experimental Motors

2022-04-29 20:09 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +			rate = 9.0
but this isn't just for you - it should be 12 if there are now 4 instead of 3. details matter.

2022-04-29 20:13 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	name = AT_Quardophant
NB-Quadophant would be better - no underscores and and consistent with NB (NecroBones)

2022-04-29 20:16 UTC, zer0Kerbal commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	name = AT_Quardophant
Adjustment - NBengineElephant-quad - I liked NB-Quadrophant better. ;)

2022-05-02 16:14 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +			rate = 9.0
gotcha, will do :)

2022-05-02 16:16 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	TechRequired = veryHeavyRocketry
Okay, will do!

2022-05-02 18:44 UTC, AtomikkuSan commented on GameData/NecroBones/ElephantEngine/Parts/QuadAtomic.cfg
> +	name = AT_Quardophant
Okay!

2022-05-02 19:32 UTC, zer0Kerbal approved these changes

2022-05-02 19:48 UTC, merged